---
- include: core.yml

- name: Common configuration for all hosts
  hosts: 'all:!localhost'
  gather_facts: True
  sudo: True
  roles:
    - role: debops.apt_preferences
      tags: [ 'apt_preferences', 'role::apt_preferences' ]

    - role: debops.etc_services
      tags: [ 'etc_services', 'role::etc_services' ]

    - role: debops.pki
      tags: [ 'pki', 'role::pki' ]

    - role: debops.auth
      tags: [ 'auth', 'role::auth' ]

    - role: debops.apt
      tags: [ 'apt', 'role::apt' ]

    - role: debops.ferm
      tags: [ 'ferm', 'role::ferm' ]

    - role: debops.tcpwrappers
      tags: [ 'tcpwrappers', 'role::tcpwrappers' ]

    - role: debops.ntp
      tags: [ 'ntp', 'role::ntp' ]

    - role: debops.console
      tags: [ 'console', 'role::console' ]

    - role: debops.postfix
      tags: [ 'postfix', 'role::postfix' ]

    - role: debops.rsyslog
      tags: [ 'rsyslog', 'role::rsyslog' ]

    - role: debops.users
      tags: [ 'users', 'role::users' ]

    - role: debops.sshkeys
      tags: [ 'sshkeys', 'role::sshkeys' ]

    - role: debops.sshd
      tags: [ 'sshd', 'role::sshd' ]

    - role: debops.directories
      tags: [ 'directories', 'role::directories' ]
