---
- name: Manage users with SFTPonly accounts
  hosts: 'sftpusers'
  become: True
  roles:
    - role: debops.sftpusers
      tags: [ 'role::sftpusers', 'sftpusers' ]

    - role: debops.sshkeys
      tags: [ 'role::sshkeys', 'sshkeys' ]
