---
- name: Manage Redis server
  hosts: 'redis'
  become: True
  roles:
    - role: debops.redis
      tags: [ 'role::redis', 'redis' ]

- name: Manage Redis sentinel server
  hosts: 'redis_sentinel'
  become: True
  roles:
    - role: debops.redis
      tags: [ 'role::redis', 'redis' ]
